import qi

session = qi.Session()
session.connect("tcp://127.0.0.1:9559")

anim = session.service("ALAnimationPlayer")

anim.run("animations/Stand/Emotions/Positive/Confident_1",_async=True)    
input("press any key")
anim.run("animations/Stand/Emotions/Positive/Interested_1",_async=True)    
input("press any key")
anim.run("animations/Stand/Gestures/Explain_11",_async=True)    
input("press any key")
anim.run("animations/Stand/Gestures/Thinking_8",_async=True)    
input("press any key")
anim.run("animations/Stand/Emotions/Negative/Shocked_1",_async=True)    
input("press any key")
anim.run("animations/Stand/Emotions/Negative/Disappointed_1",_async=True)    
input("press any key")
anim.run("animations/Stand/Emotions/Positive/Happy_4",_async=True)    
input("press any key")
anim.run("animations/Stand/Emotions/Positive/Hysterical_1",_async=True)    
input("press any key")
anim.run("animations/Stand/Gestures/Give_6",_async=True)    
input("press any key")
anim.run("animations/Stand/Emotions/Neutral/Innocent_1",_async=True)    
input("press any key")
anim.run("animations/Stand/Gestures/Desperate_1",_async=True)    
input("press any key")
